#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# There is no building process
build: off

# scripts that run after cloning repository
install:
  - sh: hash -r
  - cmd: SET PATH="C:\\Miniconda-x64";"C:\\Miniconda-x64\\Scripts";%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - cmd: conda update -q conda
  - source activate


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - sh: if [[ "$CI_LINUX" == true ]]; then codecov; fi


