#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# There is no building process
build: off

# scripts that run after cloning repository
install:
  - sh: if [[ $CI_LINUX == true ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    else
      curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -L -o miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi
  - cmd: choco install miniconda3 --params="'/AddToPath:1'"
  - cmd: export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:/c/Program Files/Git/miniconda3/bin/:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - cmd: conda update -q conda
  - source activate
  - conda env update -n bioptim -f environment.yml
  - conda activate bioptim
  - conda install pytest-cov black pytest pytest-cov codecov -cconda-forge
  - if [[ "$CI_LINUX" == true ]]; then 
      conda install xorg-libx11 xorg-libxtst -cconda-forge;
    fi
  - conda list
  - cd external
  - sh: if [[ "$CI_LINUX" == true ]]; then 
      ./acados_install_linux.sh;
    else
      ./acados_install_mac.sh;
    fi
  - cd ..

# to run your custom scripts instead of automatic tests
test_script:
  - bioptim_folder=`pwd`
  - sh: if [[ "$CI_LINUX" == true ]]; then 
      black . -l120 --exclude "external/*" --check;
    fi
  - pytest -v --color=yes --cov-report term-missing --cov=bioptim tests
  - python setup.py install
  - cd
  - python -c "import bioptim"
  - cd $bioptim_folder


#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - sh: if [[ "$CI_LINUX" == true ]]; then 
      codecov;
    fi


