# Config file for automatic testing at travis-ci.org
language: cpp
matrix:
  include:
  - os: linux
    dist: focal
  - os: osx
    osx_image: xcode7.2
  - os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
      choco install miniconda3 --params="'/AddToPath:1'";
      export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:/c/Program Files/Git/miniconda3/bin/:$PATH";
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda no
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then conda update -q conda; fi
  - source activate

install:
  - conda env update -n bioptim -f environment.yml
  - conda activate bioptim
  - conda install pytest-cov black pytest pytest-cov codecov -cconda-forge
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      conda install xorg-libx11 xorg-libxtst -cconda-forge;
    fi
  - conda list
  - cd external
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./acados_install_linux.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      ./acados_install_mac.sh;
    fi
  - cd ..
  

script:
  - bioptim_folder=`pwd`
  - black . -l120 --exclude "external/*" --check
  - pytest -v --color=yes --cov-report term-missing --cov=bioptim tests
  - python setup.py install
  - cd
  - python -c "import bioptim"
  - cd $bioptim_folder

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      codecov;
    fi

notifications:
  email:
    on_success: never
    on_failure: always
